### ISSUE TITLE
Getting build error " Argument of type 'SPHttpClientConfiguration' is not assignable to parameter of type 'SPHttpClientConfiguration'."

### ISSUE THREAD

**Issue by sravankumar1107** [devoooo4u/spfx-task-list-web-part#2]
Kindly fix the issue " Argument of type 'SPHttpClientConfiguration' is not assignable to parameter of type 'SPHttpClientConfiguration'." in the code.

**Comment by devoooo4u** [comment]
Similar issue: 
[https://sharepoint.stackexchange.com/questions/227365/tslint-error-argument-of-type-sphttpclientconfiguration-is-not-assign-able-to]([](https://sharepoint.stackexchange.com/questions/227365/tslint-error-argument-of-type-sphttpclientconfiguration-is-not-assign-able-to))

**Comment by Fareedbaba** [comment]
the mentioned solution in the shared URL still doesn't work
Can you provide any solution to the issue

**Comment by devoooo4u** [comment]
> Kindly fix the issue " Argument of type 'SPHttpClientConfiguration' is not assignable to parameter of type 'SPHttpClientConfiguration'." in the code.

Hi @sravankumar1107 ,
This issue was due to the spfx version you might be using. This solution was built on SPFX v 1.4.1.
I have updated the Package.json too. 
Steps to fix the issue: 
1. Clone the repository
2. run npm install
3. run npm i @microsoft/sp-http@v1.4.1
4. run npm dedupe
5 And finally, run gulp-serve
